language: node_js
node_js:
- '0.10'
- '0.11'
script: npm run-script test-travis
after_script:
- npm install -g coveralls@2
- cat ./coverage/lcov.info | coveralls
- npm install -g codeclimate-test-reporter
- cat ./coverage/lcov.info | codeclimate
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/e6c41c02531e19ba2969
    on_success: change
    on_failure: always
    on_start: false
addons:
  code_climate:
    repo_token:
      secure: UVg1bGvbjQj1wEudnJZygJEpiB39lU52PxFRSM5yWnsk7TRUychtTU0ePOpSQ7bwVLk5+1Z3G7b9qzAEGq5Q0qBHA8vFWxPFYQgUe2pcZ8D5l3Jmh6ylReZztP+6uI3g1CYwTSGFhdYkCPs/k7sMSh0K2sSsLEL4NRdkfG1LBDw=
